#-*-Python-*-
# Created by xiangjian at 2015/05/03 15:18
## this file is used to generate the job file
## thus it should be run after the onetwo, since it need new g-file and iterdb file generated by ONETWO
## and it should be run before profile_gen, since the jobfile is generated by this script
##args1='gyro -n %d -e . \n'%(root['INPUTS']['input.gyro']['TOROIDAL_GRID'])
##args2='#PBS -l nodes=1:ppn=%d \n'%(root['INPUTS']['input.gyro']['TOROIDAL_GRID'])
args1='profiles_gen -i iterdb -g %s \n' %(root['OUTPUTS']['ONETWOOutput']['newgfile'])
#PBS -l nodes=1:ppn=4
print args1

wokdir = str(root['INPUTS']['ProfileGenInput']['jobpg.pbs'])
print wokdir

f1 = open(wokdir)

li=[]
for line in f1:
    if not line.find('profiles_gen -i')==-1:
        li.append(args1)
    else:
        li.append(line)
f1.close()

f3 = open(wokdir,'w')

for line in li:
    f3.write(line)
    print(line)

f3.close()
